### ISSUE TITLE
Print tasks

### ISSUE THREAD

**Issue by kristofferR** [amazingmarvin/marvin-cli#1]
I used [todoist (CLI)](https://github.com/sachaos/todoist) before and the most vital command for me was `todoist --csv list --filter "(overdue | today)"` to print the tasks for today.

From what I can gather from --help that's not implemented yet. Please implement it as soon as possible if not, I really need that functionality. 

You might want to gather inspiration from that project, it's pretty easy to work with.

**Comment by amazingmarvin** [comment]
OK, I added a `marvin today` command to get tasks/projects scheduled today. And I added a `marvin list` for filtering your tasks/projects, but this won't work until the next desktop version is released.
